#!/usr/bin/env node
/**
 * Copies the contract ABI and the deployment record out of ../contracts into lib/chain/.
 *
 * The output is committed on purpose. Importing straight out of contracts/artifacts would
 * couple the Next build to Hardhat output that does not exist on a fresh clone or on Vercel,
 * so the boundary is crossed here, once, deliberately — and never at build time.
 *
 *   npm run sync:chain            # after deploying in contracts/
 *   CHAIN_ID=11155111 npm run sync:chain   # when targeting a public network
 *   CHAIN_ID=31337 npm run sync:chain
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const clientRoot = join(here, "..");
const contractsRoot = join(clientRoot, "..", "contracts");
const outDir = join(clientRoot, "lib", "chain");

// Defaults to the local dev chain. Override with CHAIN_ID when targeting a public network.
const chainId = Number(process.env.CHAIN_ID ?? 31337);

mkdirSync(outDir, { recursive: true });

// --- ABI -------------------------------------------------------------------
// Written as a .ts file with `as const` so viem can infer argument and return
// types. A plain JSON import loses that and every call becomes `unknown`.

const artifactPath = join(
  contractsRoot,
  "artifacts",
  "src",
  "AgentWallet.sol",
  "AgentWallet.json",
);

if (!existsSync(artifactPath)) {
  console.error(
    `No compiled artifact at ${artifactPath}\nRun \`npm run build\` in contracts/ first.`,
  );
  process.exit(1);
}

const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));

writeFileSync(
  join(outDir, "abi.ts"),
  `// GENERATED by client/scripts/sync-chain.mjs — do not edit.
// Source: contracts/artifacts/src/AgentWallet.sol/AgentWallet.json

export const agentWalletAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`,
);

console.log(`abi.ts        ${artifact.abi.length} entries`);

// --- Deployment record -----------------------------------------------------

const recordPath = join(contractsRoot, "deployments", `${chainId}.json`);
const targetPath = join(outDir, "deployment.json");

if (existsSync(recordPath)) {
  const record = JSON.parse(readFileSync(recordPath, "utf8"));

  // The ABIs already live in abi.ts; carrying a second copy here would let the two drift.
  delete record.abi;

  writeFileSync(targetPath, `${JSON.stringify({ deployed: true, ...record }, null, 2)}\n`);
  console.log(`deployment.json  chain ${record.chainId} @ ${record.contracts.agentWallet}`);
} else if (existsSync(targetPath)) {
  console.warn(
    `No deployment at ${recordPath} — keeping the existing deployment.json.\n` +
      `Deploy first in contracts/ (\`npm run deploy:local\` or \`npm run deploy:sepolia\`), then re-run this.`,
  );
} else {
  writeFileSync(
    targetPath,
    `${JSON.stringify(
      {
        deployed: false,
        chainId,
        deployedAt: null,
        deployBlock: "0",
        owner: null,
        agentSessionKey: null,
        contracts: { agentWallet: null, mockUsdc: null },
        policy: { perTxCap: "0", rollingCap: "0", decimals: 6 },
        counterparties: [],
      },
      null,
      2,
    )}\n`,
  );
  console.warn(
    `No deployment at ${recordPath} — wrote a not-deployed stub.\n` +
      `The app will run and explain that nothing is deployed yet.`,
  );
}
